name: mayr_local_notifications
description: "A simplified local notification plugin for Flutter - no native boilerplate, just plug and play across Android, iOS, and macOS."
version: 1.0.0
homepage: https://github.com/MayR-Labs/flutter_local_notifications
repository: https://github.com/MayR-Labs/flutter_local_notifications
issue_tracker: https://github.com/MayR-Labs/flutter_local_notifications/issues
documentation: https://github.com/MayR-Labs/flutter_local_notifications/wiki

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mayrlabs.mayr_local_notifications
        pluginClass: MayrLocalNotificationsPlugin
      ios:
        pluginClass: MayrLocalNotificationsPlugin
      linux:
        pluginClass: MayrLocalNotificationsPlugin
      macos:
        pluginClass: MayrLocalNotificationsPlugin
      windows:
        pluginClass: MayrLocalNotificationsPluginCApi

topics:
  - flutter
  - notifications
  - local-notifications
  - cross-platform
  - plugin
